/**
 * Observability module — Langfuse client singleton and trace factory.
 *
 * All exports are no-ops when LANGFUSE_ENABLED=false (the default in tests and CI).
 * The Langfuse client is initialised lazily on first use so env vars loaded by
 * dotenv.config() in the entry point are available before the constructor runs.
 *
 * Usage:
 *   const { trace, handler } = startTrace({ name: 'memory-pipeline-pr', sessionId, input, tags });
 *   await filterPR(pr, { langfuseHandler: handler });
 *   trace.update({ output: result });
 *   await getLangfuse().flushAsync();
 */

import Langfuse from 'langfuse';
import { CallbackHandler } from 'langfuse-langchain';
import type { LangfuseTraceClient } from 'langfuse';

// Lazy singleton — created on first call so dotenv vars are available
let _client: Langfuse | undefined;

/**
 * Returns the shared Langfuse client, creating it on first call.
 * Reads LANGFUSE_PUBLIC_KEY, LANGFUSE_SECRET_KEY, LANGFUSE_HOST, and LANGFUSE_ENABLED
 * from process.env at call time (not at module-load time).
 *
 * @example
 * ```typescript
 * const { trace } = startTrace({ name: 'my-workflow' });
 * await getLangfuse().flushAsync();
 * ```
 */
export function getLangfuse(): Langfuse {
  if (_client === undefined) {
    _client = new Langfuse({
      publicKey: process.env.LANGFUSE_PUBLIC_KEY,
      secretKey: process.env.LANGFUSE_SECRET_KEY,
      baseUrl: process.env.LANGFUSE_HOST ?? 'https://cloud.langfuse.com',
      enabled: process.env.LANGFUSE_ENABLED !== 'false',
    });
  }
  return _client;
}

/** Options for {@link startTrace}. */
export interface StartTraceOptions {
  /** Descriptive trace name — NOT unique. Groups traces of the same shape in the UI. */
  name: string;
  /** Session identifier grouping all traces from one workflow run. */
  sessionId?: string;
  /** Identity/context only — never the full scraped payload (see No-PII note in docs/observability.md). */
  input?: unknown;
  /** Tags scoping the workflow + entity, e.g. ['memory-pipeline', repo]. */
  tags?: string[];
}

/** A trace plus a LangChain callback handler rooted on it. */
export interface StartedTrace {
  trace: LangfuseTraceClient;
  handler: CallbackHandler;
}

/**
 * Create a trace and a LangChain CallbackHandler rooted on it.
 *
 * The trace ID is generated by Langfuse — never derive it from entity identity
 * (e.g. a PR number). A reused ID across runs silently corrupts session grouping
 * when the same entity is reprocessed. Keep identity in `input`/`tags` instead.
 *
 * The SDK no-ops automatically when LANGFUSE_ENABLED=false, so the returned
 * handler can be passed unconditionally to any LangChain chain.invoke() call to
 * capture token counts, latency, and model names.
 *
 * @example
 * ```typescript
 * const { trace, handler } = startTrace({
 *   name: 'memory-pipeline-pr',
 *   sessionId,
 *   input: { prNum, repo, url },
 *   tags: ['memory-pipeline', repo],
 * });
 * await chain.invoke(prompt, { callbacks: [handler] });
 * const span = trace.span({ name: 'scrape' });
 * span.end({ output });
 * trace.update({ output: result });
 * await getLangfuse().flushAsync();
 * ```
 */
export function startTrace(opts: StartTraceOptions): StartedTrace {
  const trace = getLangfuse().trace({
    name: opts.name,
    sessionId: opts.sessionId,
    input: opts.input,
    tags: opts.tags,
  });
  const handler = new CallbackHandler({ root: trace });
  return { trace, handler };
}
