import {
  CodeGenModule,
  CodeGenModuleInput,
  CodeGenModuleOutput,
  GeneratedFile,
} from '../../interface';

function readEnv(name: string): string | undefined {
  const runtime = globalThis as { process?: { env?: Record<string, string | undefined> } };
  return runtime.process?.env?.[name];
}

export class ClaudeApiCodeGenModule implements CodeGenModule {
  name = 'claude-api';

  version = '0.1.0';

  async generate(input: CodeGenModuleInput): Promise<CodeGenModuleOutput> {
    const suggestedPath = `${input.targetDirectory.replace(/\/$/, '')}/IMPLEMENTATION_PLAN.md`;
    const file = this.buildPlanFile(input, suggestedPath);

    return {
      files: [file],
      explanation:
        'Generated an implementation-plan artifact from ticket, research findings, and orchestration plan.',
      modelUsed: readEnv('ANTHROPIC_MODEL') || 'claude-sonnet-4-20250514',
    };
  }

  async validate(): Promise<boolean> {
    return Boolean(readEnv('ANTHROPIC_API_KEY'));
  }

  private buildPlanFile(input: CodeGenModuleInput, outputPath: string): GeneratedFile {
    const phaseLines = input.orchestrationPlan.phases
      .map(
        (phase, index) =>
          `${index + 1}. ${phase.name} (${phase.estimatedComplexity}) - ${phase.description}`
      )
      .join('\n');

    const content = [
      '# Generated Implementation Plan',
      '',
      `Ticket: ${input.ticket.issue.title}`,
      `Priority: ${input.ticket.issue.priority}`,
      `Target Directory: ${input.targetDirectory}`,
      '',
      '## Proposed Approach',
      input.orchestrationPlan.proposedApproach,
      '',
      '## Suggested Phases',
      phaseLines || 'No phases were provided.',
      '',
      '## Key Findings',
      input.orchestrationPlan.keyFindings.length > 0
        ? input.orchestrationPlan.keyFindings.map((finding) => `- ${finding}`).join('\n')
        : '- No key findings were provided.',
      '',
      '## Documentation Sources',
      input.researchFindings.documentationReferences.length > 0
        ? input.researchFindings.documentationReferences.map((ref) => `- [${ref.title}](${ref.url})`).join(
          '\n'
        )
        : '- No documentation references were provided.',
      '',
    ].join('\n');

    return {
      path: outputPath,
      content,
      purpose: 'Implementation planning artifact generated by claude-api module',
    };
  }
}

export const claudeApiCodeGenModule = new ClaudeApiCodeGenModule();
